plugins {
    id 'java'
    id 'idea'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '4.2.34'
}

group = 'com.reto'
version = '1.0'

repositories {
    mavenCentral()
}

ext {
    serenityVersion = '4.2.34'
}

dependencies {

    testImplementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-junit5:${serenityVersion}"

    testImplementation "net.serenity-bdd:serenity-screenplay:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay-rest:${serenityVersion}"

    testImplementation "net.serenity-bdd:serenity-cucumber:${serenityVersion}"

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

test {
    useJUnitPlatform()
}